[package]
name = "wow_vr_lib"
version = "0.0.1"
edition = "2024"

[dependencies]
bitflags = { workspace = true }
byteorder = { workspace = true }
flate2 = { workspace = true }
once_cell = { workspace = true }
thiserror = { workspace = true }
